Lineage pull request for: skeleton
cisagov/ansible-role-cdm-nessus-agent pull request #15
Opened 2021-08-24 14:34 UTC by cisagovbot

# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-ansible-role-with-test-user.git`](https://github.com/cisagov/skeleton-ansible-role-with-test-user.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2021-08-24 15:33 UTC, jsf9k approved these changes

2021-08-24 15:37 UTC, dav3r requested changes
There are some role variables here that need to be tabulated.

2021-08-24 15:37 UTC, dav3r commented on README.md
> +
You missed some role variables in here.

2021-08-24 17:59 UTC, dav3r approved these changes

2021-08-25 14:08 UTC, mcdonnnj approved these changes

2021-08-25 14:11 UTC, merged